#!/bin/bash

echo Enter First name
read FIRST

echo Enter Last name
read LAST

while true
do
	echo Enter username
	read USERNAME123
	
	if [ -n "$USERNAME123" ]
	then
		break
	fi
done

echo $FIRST $LAST $USERNAME123
